name: Nightly Docs
on:
  push: null
jobs:
  ansible-docs:
    runs-on: ubuntu-latest
    name: Publish ansible-based docs
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ansible
    - name: Run publish docs script
      env:
        PULP_DOCS_KEY: ${{ secrets.PULP_DOCS_KEY }}
      run: .ci/scripts/publish_docs.sh ansible
    - uses: actions/checkout@v3
    - name: Run publish docs script
      env:
        PULP_DOCS_KEY: ${{ secrets.PULP_DOCS_KEY }}
      run: .ci/scripts/publish_docs.sh ${GITHUB_REF##*/}
